openapi: 3.0.0
info:
  version: '2023-11-26'
  title: Amazon EKS Auth
  description: Amazon EKS Auth
  x-serviceName: eks-auth
  x-serviceAlias: eks_auth
  x-protocol: rest-json
  x-apiVersion: '2023-11-26'
  x-endpointPrefix: eks-auth
  x-jsonVersion: '1.1'
servers:
- url: https://eks-auth.{region}.amazonaws.com
  variables:
    region:
      default: us-east-1
      description: AWS region
  description: Regional endpoint for eks-auth
paths:
  /clusters/{cluster_name}/assume-role-for-pod-identity:
    post:
      operationId: AssumeRoleForPodIdentity
      description: The Amazon EKS Auth API and the AssumeRoleForPodIdentity action are only used by the EKS Pod Identity Agent.
        We recommend that applications use the Amazon Web Services SDKs to connect to Amazon Web Services services; if credentials
        from an EKS Pod Identity association are available in the pod, the latest versions of the SDKs use them automatically.
      parameters:
      - name: cluster_name
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/ClusterName'
        description: The name of the cluster for the request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  $ref: '#/components/schemas/JwtToken'
              required:
              - token
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssumeRoleForPodIdentityResponse'
      x-stackql-resource: assume_role_for_pod_identity
      x-stackql-method: assume_role_for_pod_identity
      x-stackql-verb: EXEC
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ClusterName:
      type: string
      minLength: 1
      maxLength: 100
      pattern: '[0-9A-Za-z][A-Za-z0-9\-_]*'
    JwtToken:
      type: string
      minLength: 1
      pattern: '[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+'
    AssumeRoleForPodIdentityResponse:
      type: object
      properties:
        subject:
          $ref: '#/components/schemas/Subject'
          description: The name of the Kubernetes service account inside the cluster to associate the IAM credentials with.
        audience:
          $ref: '#/components/schemas/String'
          description: The identity that is allowed to use the credentials. This value is always pods.eks.amazonaws.com.
        podIdentityAssociation:
          $ref: '#/components/schemas/PodIdentityAssociation'
          description: The Amazon Resource Name (ARN) and ID of the EKS Pod Identity association.
        assumedRoleUser:
          $ref: '#/components/schemas/AssumedRoleUser'
          description: 'An object with the permanent IAM role identity and the temporary session name. The ARN of the IAM
            role that the temporary credentials authenticate to. The session name of the temporary session requested to STS.
            The value is a unique identifier that contains the role ID, a colon (:), and the role session name of the role
            that is being assumed. The role ID is generated by IAM when the role is created. The role session name part of
            the value follows this format: eks-clustername-podname-random UUID'
        credentials:
          $ref: '#/components/schemas/Credentials'
          description: The Amazon Web Services Signature Version 4 type of temporary credentials.
      required:
      - subject
      - audience
      - podIdentityAssociation
      - assumedRoleUser
      - credentials
    Subject:
      description: An object containing the name of the Kubernetes service account inside the cluster to associate the IAM
        credentials with.
      type: object
      properties:
        namespace:
          $ref: '#/components/schemas/String'
          description: The name of the Kubernetes namespace inside the cluster to create the association in. The service account
            and the pods that use the service account must be in this namespace.
        serviceAccount:
          $ref: '#/components/schemas/String'
          description: The name of the Kubernetes service account inside the cluster to associate the IAM credentials with.
      required:
      - namespace
      - serviceAccount
    String:
      type: string
    PodIdentityAssociation:
      description: Amazon EKS Pod Identity associations provide the ability to manage credentials for your applications, similar
        to the way that Amazon EC2 instance profiles provide credentials to Amazon EC2 instances.
      type: object
      properties:
        associationArn:
          $ref: '#/components/schemas/String'
          description: The Amazon Resource Name (ARN) of the EKS Pod Identity association.
        associationId:
          $ref: '#/components/schemas/String'
          description: The ID of the association.
      required:
      - associationArn
      - associationId
    AssumedRoleUser:
      description: An object with the permanent IAM role identity and the temporary session name.
      type: object
      properties:
        arn:
          $ref: '#/components/schemas/String'
          description: The ARN of the IAM role that the temporary credentials authenticate to.
        assumeRoleId:
          $ref: '#/components/schemas/String'
          description: 'The session name of the temporary session requested to STS. The value is a unique identifier that
            contains the role ID, a colon (:), and the role session name of the role that is being assumed. The role ID is
            generated by IAM when the role is created. The role session name part of the value follows this format: eks-clustername-podname-random
            UUID'
      required:
      - arn
      - assumeRoleId
    Credentials:
      description: The Amazon Web Services Signature Version 4 type of temporary credentials.
      type: object
      properties:
        sessionToken:
          $ref: '#/components/schemas/String'
          description: The token that applications inside the pods must pass to any service API to use the temporary credentials.
        secretAccessKey:
          $ref: '#/components/schemas/String'
          description: The secret access key that applications inside the pods use to sign requests.
        accessKeyId:
          $ref: '#/components/schemas/String'
          description: The access key ID that identifies the temporary security credentials.
        expiration:
          $ref: '#/components/schemas/Timestamp'
          description: The Unix epoch timestamp in seconds when the current credentials expire.
      required:
      - sessionToken
      - secretAccessKey
      - accessKeyId
      - expiration
    Timestamp:
      type: string
      format: date-time
