openapi: 3.0.0
info:
  version: '2018-06-26'
  title: Amazon Forecast Query Service
  description: Amazon Forecast Query Service
  x-serviceName: forecast
  x-serviceAlias: forecastquery
  x-protocol: json
  x-apiVersion: '2018-06-26'
  x-endpointPrefix: forecastquery
  x-targetPrefix: AmazonForecastRuntime
  x-jsonVersion: '1.1'
servers:
- url: https://forecastquery.{region}.amazonaws.com
  variables:
    region:
      default: us-east-1
      description: AWS region
  description: Regional endpoint for forecastquery
paths:
  /QueryForecast:
    post:
      operationId: QueryForecast
      description: Retrieves a forecast for a single item, filtered by the supplied criteria. The criteria is a key-value
        pair. The key is either item_id (or the equivalent non-timestamp, non-target field) from the TARGET_TIME_SERIES dataset,
        or one of the forecast dimensions specified as part of the FeaturizationConfig object. By default, QueryForecast returns
        the complete date range for the filtered forecast. You can request a specific date range. To get the full forecast,
        use the CreateForecastExportJob operation. The forecasts generated by Amazon Forecast are in the same timezone as
        the dataset that was used to create the predictor.
      parameters:
      - name: X-Amz-Target
        in: header
        description: Action Header
        required: false
        schema:
          type: string
          enum:
          - AmazonForecastRuntime.QueryForecast
          default: AmazonForecastRuntime.QueryForecast
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ForecastArn:
                  $ref: '#/components/schemas/Arn'
                  description: The Amazon Resource Name (ARN) of the forecast to query.
                StartDate:
                  $ref: '#/components/schemas/DateTime'
                  description: 'The start date for the forecast. Specify the date using this format: yyyy-MM-dd''T''HH:mm:ss
                    (ISO 8601 format). For example, 2015-01-01T08:00:00.'
                EndDate:
                  $ref: '#/components/schemas/DateTime'
                  description: 'The end date for the forecast. Specify the date using this format: yyyy-MM-dd''T''HH:mm:ss
                    (ISO 8601 format). For example, 2015-01-01T20:00:00.'
                Filters:
                  $ref: '#/components/schemas/Filters'
                  description: 'The filtering criteria to apply when retrieving the forecast. For example, to get the forecast
                    for client_21 in the electricity usage dataset, specify the following: {"item_id" : "client_21"} To get
                    the full forecast, use the CreateForecastExportJob operation.'
                NextToken:
                  $ref: '#/components/schemas/NextToken'
                  description: If the result of the previous request was truncated, the response includes a NextToken. To
                    retrieve the next set of results, use the token in the next request. Tokens expire after 24 hours.
              required:
              - ForecastArn
              - Filters
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryForecastResponse'
      x-stackql-resource: query_forecast
      x-stackql-method: query_forecast
      x-stackql-verb: EXEC
  /QueryWhatIfForecast:
    post:
      operationId: QueryWhatIfForecast
      description: Retrieves a what-if forecast.
      parameters:
      - name: X-Amz-Target
        in: header
        description: Action Header
        required: false
        schema:
          type: string
          enum:
          - AmazonForecastRuntime.QueryWhatIfForecast
          default: AmazonForecastRuntime.QueryWhatIfForecast
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                WhatIfForecastArn:
                  $ref: '#/components/schemas/LongArn'
                  description: The Amazon Resource Name (ARN) of the what-if forecast to query.
                StartDate:
                  $ref: '#/components/schemas/DateTime'
                  description: 'The start date for the what-if forecast. Specify the date using this format: yyyy-MM-dd''T''HH:mm:ss
                    (ISO 8601 format). For example, 2015-01-01T08:00:00.'
                EndDate:
                  $ref: '#/components/schemas/DateTime'
                  description: 'The end date for the what-if forecast. Specify the date using this format: yyyy-MM-dd''T''HH:mm:ss
                    (ISO 8601 format). For example, 2015-01-01T20:00:00.'
                Filters:
                  $ref: '#/components/schemas/Filters'
                  description: 'The filtering criteria to apply when retrieving the forecast. For example, to get the forecast
                    for client_21 in the electricity usage dataset, specify the following: {"item_id" : "client_21"} To get
                    the full what-if forecast, use the CreateForecastExportJob operation.'
                NextToken:
                  $ref: '#/components/schemas/NextToken'
                  description: If the result of the previous request was truncated, the response includes a NextToken. To
                    retrieve the next set of results, use the token in the next request. Tokens expire after 24 hours.
              required:
              - WhatIfForecastArn
              - Filters
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryWhatIfForecastResponse'
      x-stackql-resource: query_what_if_forecast
      x-stackql-method: query_what_if_forecast
      x-stackql-verb: EXEC
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    Arn:
      type: string
      maxLength: 256
      pattern: arn:([a-z\d-]+):forecast:.*:.*:.+
    DateTime:
      type: string
    Filters:
      type: object
      properties: {}
    NextToken:
      type: string
      minLength: 1
      maxLength: 3000
    QueryForecastResponse:
      type: object
      properties:
        Forecast:
          $ref: '#/components/schemas/Forecast'
          description: The forecast.
    Forecast:
      description: Provides information about a forecast. Returned as part of the QueryForecast response.
      type: object
      properties:
        Predictions:
          type: object
          properties: {}
          description: 'The forecast. The string of the string-to-array map is one of the following values: p10 p50 p90 The
            default setting is ["0.1", "0.5", "0.9"]. Use the optional ForecastTypes parameter of the CreateForecast operation
            to change the values. The values will vary depending on how this is set, with a minimum of 1 and a maximum of
            5.'
    LongArn:
      type: string
      maxLength: 300
      pattern: arn:([a-z\d-]+):forecast:.*:.*:.+
    QueryWhatIfForecastResponse:
      type: object
      properties:
        Forecast:
          $ref: '#/components/schemas/Forecast'
